app/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
app_name ='app'
urlpatterns= [
    path('', home,name="home"), 
    path('register/', register,name="register"),
    path('login/', loginPage,name="login"),
    path('logout/', logoutPage,name="logout"),
    path('cart/', cart,name="cart"), 
    path('checkout/', checkout,name="checkout"), 
    path('viewCartcheckout/', viewCartcheckout, name='viewCartcheckout'),
    path('product_detail/<int:id>', product_detail,name="product_detail"), 
    path('contact/', contact,name="contact"), 
    path('update_item/', updateItem,name="update_item"), 
    path('addCart/<int:product_id>/', addCart, name='addCart'),
    path('removeCart/<int:id>',removeCart, name='removeCart' ),
    # path('updateCart-cart/<int:id>',updateCart, name='updateCart'),
    path('checkout/', checkout, name='checkout'),
]

pythonClock/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('app.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app/controllers/CartController.py
import random
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect
from models import *
def cart(request):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('login'))
    else:
        user = request.user
        categoryList = Category.objects.all()
        # nếu order null thì total = 0
        try:
            order = Order.objects.filter(is_paid=False, user=user).first()
            cart_items = OrderDetail.objects.filter(order=order)
            total_price = order.get_cart_total()
        except AttributeError:
            order = None
            cart_items = None
            total_price = 0
        context = {'cart_items': cart_items,
                   'total_price': total_price, 'categoryList': categoryList}
    return render(request, 'pages/cart.html', context)

def addCart(request, product_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('login'))
    else:
        user = request.user
        product = get_object_or_404(Product, id=product_id)
        order, _ = Order.objects.get_or_create(user=user)
        order_details = OrderDetail.objects.filter(order=order, product=product)

        if order_details.exists():
            order_detail = order_details.first()
            order_detail.quantity += 1
            order_detail.save()
        else:
            order_detail = OrderDetail(order=order, product=product, quantity = 1)
            order_detail.save()

        # Chuyển người dùng đến trang giỏ hàng
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def checkout(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        address = request.POST.get('address')
        phone = request.POST.get('phone')
        note = request.POST.get('note')
        user = request.user
        order = Order.objects.filter(is_paid=False, user=user).first()
        if order:
            order.is_paid = True
            order.save()
        total = 0
        customer = ShippingAddress.objects.create(
            name=name, address=address, phone=phone, note=note, total=total)
        if customer:
            customer.user = request.user
            customer.order = order
            customer.save()
        order.customer = customer
        order.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        return render(request, 'app/checkout.html')

app/templates/app/cart.html
{% extends 'app/base.html' %}
{% load static %}
{% block cart-content %}
<!-- Breadcrumb Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" href="#">Home</a>
                <a class="breadcrumb-item text-dark" href="#">Shop</a>
                <span class="breadcrumb-item active">Shopping Cart</span>
            </nav>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->


<!-- Cart Start -->
<div class="container-fluid">
    <div class="row px-xl-5">

        <div class="col-lg-8 table-responsive mb-5">

            <table class="table table-light table-borderless table-hover text-center mb-0">
                <thead class="thead-dark">
                    <tr>
                        <th></th>
                        <th>Name</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                {%for details in cart_items%}
                <tbody class="align-middle">
                    <tr>

                        <td class="align-middle"><img src="{{details.product.ImageURL}}" alt="" style="width: 50px;">
                        </td>
                        <td class="align-middle">{{details.product.name}}</td>
                        <td class="align-middle">{{details.product.price}}</td>
                        <td class="align-middle">
                            <div class="input-group quantity mx-auto" style="width: 100px;">
                                <div class="input-group-btn">
                                    <button data-product = {{item.product.id}} data-action = 'add' class="btn btn-sm btn-primary btn-minus update-cart">
                                        <i class="fa fa-minus"></i>
                                    </button>
                                </div>
                                <input type="text"
                                    class="form-control form-control-sm bg-secondary border-0 text-center" value="{{details.quantity}}">
                                <div class="input-group-btn">
                                    <button data-product = {{item.product.id}} data-action = 'remove' class="btn btn-sm btn-primary btn-plus update-cart">
                                        <i class="fa fa-plus"></i>
                                    </button>
                                </div>
                            </div>
                        </td>
                        <td class="align-middle">{{details.get_total}}</td>
                        <td class="align-middle"><a href="{% url 'app:removeCart' details.id%}"><button class="btn btn-sm btn-danger"><i
                                    class="fa fa-times"></i></button></a></td>
                    </tr>

                </tbody>
                {%endfor%}
            </table>

        </div>

        <div class="col-lg-4">
            <form class="mb-30" action="">
                <div class="input-group">
                    <input type="text" class="form-control border-0 p-4" placeholder="Coupon Code">
                    <div class="input-group-append">
                        <button class="btn btn-primary">Apply Coupon</button>
                    </div>
                </div>
            </form>
            <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart
                    Summary</span></h5>
            <div class="bg-light p-30 mb-5">
                <div class="border-bottom pb-2">
                    <div class="d-flex justify-content-between mb-3">
                        <h6>Items</h6>
                        <h6>{{items}}</h6>
                    </div>
                    <div class="d-flex justify-content-between mb-3">
                        <h6>Subtotal</h6>
                        <h6>{{total_price}}</h6>
                    </div>
                    <div class="d-flex justify-content-between">
                        <h6 class="font-weight-medium">Shipping</h6>
                        <h6 class="font-weight-medium">$10</h6>
                    </div>
                </div>
                <div class="pt-2">
                    <div class="d-flex justify-content-between mt-2">
                        <h5>Total</h5>
                        <h5>{{total_price}}</h5>
                    </div>
                    <button class="btn btn-block btn-primary font-weight-bold my-3 py-3"><a class="colora"
                            href="{% url 'app:checkout' %}">To Checkout</a> </button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Cart End -->
{% endblock cart-content %}

app/templates/app/checkout.html
{% extends 'app/base.html' %}
{% load static %}
{% block checkout-content %}
<!-- Breadcrumb Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" href="#">Home</a>
                <a class="breadcrumb-item text-dark" href="#">Shop</a>
                <span class="breadcrumb-item active">Checkout</span>
            </nav>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->


<!-- Checkout Start -->
<div class="container-fluid">
    <form id="checkoutForm" method="POST"  action="{% url 'app:checkout' %}"
            data-bind-event-submit="handleCheckoutSubmit(event)"
            data-bind-event-keypress="handleCheckoutKeyPress(event)"
            data-bind-event-change="handleCheckoutChange(event)">
            {% csrf_token %}
    <div class="row px-xl-5 checkout" data-tg-refresh="checkout" id="checkout">
        
            
                <div class="col-lg-8">
                    <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Thông tin nhận hàng</span></h5>
                    <div class="bg-light p-30 mb-5">
                        <div class="row">
                            <div class="col-md-12 form-group">
                                <label> Họ và tên</label>
                                <input class="form-control" type="text" placeholder="Trần Văn A">
                            </div>
                            
                            
                            <div class="col-md-12 form-group">
                                <label>Số điện thoại</label>
                                <input class="form-control" type="text" placeholder="+123 456 789">
                            </div>
                            <div class="col-md-12 form-group">
                                <label>Địa chỉ</label>
                                <input class="form-control" type="text" placeholder="123 Street">
                            </div>
                            <div class="col-md-12 form-group">
                                <label>Ghi chú</label>
                                <input class="form-control" type="text" placeholder="Ghi chú ...">
                            </div>
                           
                            <div class="col-md-12">
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" id="shipto">
                                    <label class="custom-control-label" for="shipto"  data-toggle="collapse" data-target="#shipping-address">Ship to different address</label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="collapse mb-5" id="shipping-address">
                        <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Shipping Address</span></h5>
                        <div class="bg-light p-30">
                            <div class="row">
                                <div class="col-md-6 form-group">
                                    <label>First Name</label>
                                    <input class="form-control" type="text" placeholder="John">
                                </div>
                                <div class="col-md-6 form-group">
                                    <label>Last Name</label>
                                    <input class="form-control" type="text" placeholder="Doe">
                                </div>
                                <div class="col-md-6 form-group">
                                    <label>E-mail</label>
                                    <input class="form-control" type="text" placeholder="example@email.com">
                                </div>
                                <div class="col-md-6 form-group">
                                    <label>Mobile No</label>
                                    <input class="form-control" type="text" placeholder="+123 456 789">
                                </div>
                                <div class="col-md-6 form-group">
                                    <label>Address Line 1</label>
                                    <input class="form-control" type="text" placeholder="123 Street">
                                </div>
                                <div class="col-md-6 form-group">
                                    <label>Address Line 2</label>
                                    <input class="form-control" type="text" placeholder="123 Street">
                                </div>
                                <div class="col-md-6 form-group">
                                    <label>Country</label>
                                    <select class="custom-select">
                                        <option selected>United States</option>
                                        <option>Afghanistan</option>
                                        <option>Albania</option>
                                        <option>Algeria</option>
                                    </select>
                                </div>
                                <div class="col-md-6 form-group">
                                    <label>City</label>
                                    <input class="form-control" type="text" placeholder="New York">
                                </div>
                                <div class="col-md-6 form-group">
                                    <label>State</label>
                                    <input class="form-control" type="text" placeholder="New York">
                                </div>
                                <div class="col-md-6 form-group">
                                    <label>ZIP Code</label>
                                    <input class="form-control" type="text" placeholder="123">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Order Total</span></h5>
                    <div class="bg-light p-30 mb-5">
                        <h6 class="mb-3">Products</h6>
                        {%for detail in cart_items %}
                        <div class="border-bottom">
                            
                            <div class="d-flex justify-content-between">
                                <p><img src="{{detail.product.ImageURL}}" alt="" style="width: 50px;"></p>
                                <p>{{detail.product.name}}</p>
                                <p>{{detail.product.price}}</p>
                            </div>
                            
                        </div>
                        {%endfor%}
                        <div class="border-bottom pt-3 pb-2">
                            <div class="d-flex justify-content-between mb-3">
                                <h6>Items</h6>
                                <h6>{{order.get_cart_items}}</h6>
                            </div>
                            <div class="d-flex justify-content-between">
                                <h6 class="font-weight-medium">Shipping</h6>
                                <h6 class="font-weight-medium">$10</h6>
                            </div>
                        </div>
                        <div class="pt-2">
                            <div class="d-flex justify-content-between mt-2">
                                <h5>Total</h5>
                                <h5>{{order.get_cart_total}}</h5>
                            </div>
                        </div>
                    </div>
                    <div class="mb-5">
                        <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Payment</span></h5>
                        <div class="bg-light p-30">
                            <div class="form-group">
                                <div class="custom-control custom-radio">
                                    <input type="radio" class="custom-control-input" name="payment" id="paypal">
                                    <label class="custom-control-label" for="paypal">Paypal</label>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="custom-control custom-radio">
                                    <input type="radio" class="custom-control-input" name="payment" id="directcheck">
                                    <label class="custom-control-label" for="directcheck">Direct Check</label>
                                </div>
                            </div>
                            <div class="form-group mb-4">
                                <div class="custom-control custom-radio">
                                    <input type="radio" class="custom-control-input" name="payment" id="banktransfer">
                                    <label class="custom-control-label" for="banktransfer">Bank Transfer</label>
                                </div>
                            </div>
                            <button class="btn btn-block btn-primary font-weight-bold py-3">Place Order</button>
                        </div>
                    </div>
                </div>
            
        
    </div>
</form>
</div>
<!-- Checkout End -->
{% endblock checkout-content %}

app/templates/app/contact.html
{% extends 'app/base.html' %}
{% load static %}
{% block contact-content %}
<!-- Breadcrumb Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" href="#">Home</a>
                <span class="breadcrumb-item active">Contact</span>
            </nav>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->


<!-- Contact Start -->
<div class="container-fluid">
    <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Contact Us</span></h2>
    <div class="row px-xl-5">
        <div class="col-lg-7 mb-5">
            <div class="contact-form bg-light p-30">
                <div id="success"></div>
                <form name="sentMessage" id="contactForm" novalidate="novalidate">
                    <div class="control-group">
                        <input type="text" class="form-control" id="name" placeholder="Your Name"
                            required="required" data-validation-required-message="Please enter your name" />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="control-group">
                        <input type="email" class="form-control" id="email" placeholder="Your Email"
                            required="required" data-validation-required-message="Please enter your email" />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="control-group">
                        <input type="text" class="form-control" id="subject" placeholder="Subject"
                            required="required" data-validation-required-message="Please enter a subject" />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="control-group">
                        <textarea class="form-control" rows="8" id="message" placeholder="Message"
                            required="required"
                            data-validation-required-message="Please enter your message"></textarea>
                        <p class="help-block text-danger"></p>
                    </div>
                    <div>
                        <button class="btn btn-primary py-2 px-4" type="submit" id="sendMessageButton">Send
                            Message</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-lg-5 mb-5">
            <div class="bg-light p-30 mb-30">
                <iframe style="width: 100%; height: 250px;"
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3001156.4288297426!2d-78.01371936852176!3d42.72876761954724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4ccc4bf0f123a5a9%3A0xddcfc6c1de189567!2sNew%20York%2C%20USA!5e0!3m2!1sen!2sbd!4v1603794290143!5m2!1sen!2sbd"
                frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
            </div>
            <div class="bg-light p-30 mb-3">
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                <p class="mb-2"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
            </div>
        </div>
    </div>
</div>
<!-- Contact End -->
{% endblock contact-content %}

app/templates/app/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
   
    <link rel="stylesheet" href="{%static 'app/lib/bootstrap/dist/css/bootstrap.min.css'%}" />
    <link rel="stylesheet" href="{%static 'app/css/site.css'%}"  />
    <link rel="stylesheet" href="{%static 'app/adminlg/vendor/fontawesome-free/css/all.min.css'%}" asp-append-version="true" type="text/css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          asp-append-version="true" />

    <!-- Custom styles for this template-->
    <link rel="stylesheet" href="{%static 'app/adminlg/css/sb-admin-2.min.css'%}" asp-append-version="true" />

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <img src="{%static 'app/img/catHublot.jpg'%}" class="col-lg-6 d-none d-lg-block bg-login-image" />
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Login</h1>
                                    </div>
                                    <form asp-action="Login" method="POST" class="user">
                                        {% csrf_token %}
                                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                        <div class="form-group">

                                            <input asp-for="username" name="username" class="form-control form-control-user" placeholder="Username" />
                                            <span asp-validation-for="username" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">

                                            <input asp-for="password" name="password" type="password" class="form-control form-control-user" placeholder="Password" />
                                            <span asp-validation-for="password" class="text-danger"></span>

                                        </div>
                                        

                                        <input type="submit" value="Login" class="btn btn-primary btn-user btn-block" />
                                        {%for message in messages%}
                                        <p class=" btn-user btn-block" id="message">{{message}}</p>
                                        {%endfor%}
                                     
                                        <hr>
                                        <a href="index.html" class="btn btn-google btn-user btn-block">
                                            <i class="fab fa-google fa-fw"></i> Login with Google
                                        </a>
                                        <a href="index.html" class="btn btn-facebook btn-user btn-block">
                                            <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook
                                        </a>

                                        
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="forgot-password.html">Forgot Password?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'register'%}">Create an Account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>
    <script src="{%static 'app/lib/jquery/dist/jquery.min.js'%}"></script>
    <script src="{%static 'app/lib/bootstrap/dist/js/bootstrap.bundle.min.js'%}"></script>
    <script src="{%static 'app/js/site.js'%}" asp-append-version="true"></script>
    <script src="{%static 'app/adminlg/vendor/jquery/jquery.min.js'%}"></script>
    <script src="{%static 'app/adminlg/vendor/bootstrap/js/bootstrap.bundle.min.js'%}" asp-append-version="true"></script>
    <script src="{%static 'app/adminlg/vendor/jquery-easing/jquery.easing.min.js'%}" asp-append-version="true"></script>
    <script src="{%static 'app/adminlg/js/sb-admin-2.min.js'%}" asp-append-version="true"></script>
    <script src="{%static 'app/adminlg/vendor/chart.js/Chart.min.js'%}" asp-append-version="true"></script>
    <script src="{%static 'app/adminlg/js/demo/chart-area-demo.js'%}" asp-append-version="true"></script>
    <script src="{%static 'app/adminlg/js/demo/chart-pie-demo.js'%}" asp-append-version="true"></script>




</body>

</html>

   